spring.application.name=springboot-plantilla
server.port=8080

spring.mvc.problemdetails.enabled=true
spring.data.web.pageable.default-page-size=20

spring.cache.type=caffeine
spring.cache.cache-names=tareas_list,tareas_id
spring.cache.caffeine.spec=maximumSize=100,expireAfterWrite=10m

# Configuración de PostgreSQL para Render (usa la External Database URL)
spring.datasource.url=jdbc:postgresql://localhost:5432/dbtareas
spring.datasource.username=neisser
spring.datasource.password=12345678

# Configuración específica de PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true